name: shareable_module
description: A new Flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  syncfusion_flutter_barcodes: ^23.2.6
  loading_service:
    git: 
      url: git@github.com:niypoo/loading_service.git
  firestore_service:
    git: 
      url: git@github.com:niypoo/firestore_service.git
  realtime_database_service:
    git: 
      url: git@github.com:niypoo/realtime_database_service.git
  qr_code_scanner_module:
    git: 
      url:  git@github.com:niypoo/qr_code_scanner_module.git
  bottom_sheet_helper:
    git: 
      url: git@github.com:niypoo/bottom_sheet_helper.git
  snackbar_helper:
    git: 
      url:  git@github.com:niypoo/snackbar_helper.git
  helpers:
    git: 
      url:  git@github.com:niypoo/helpers.git
  dynamic_links_helper:
    git: 
      url:  git@github.com:niypoo/dynamic_links_helper.git
  share_helper:
    git: 
      url:  git@github.com:niypoo/share_helper.git
  fly_ui:
    git:
      url: git@github.com:niypoo/fly_ui.git
  firebase_authentication_service:
    git: 
      url:  git@github.com:niypoo/firebase_authentication_service.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
